[package]
name = "zeusns"
version = "0.1.0"
edition = "2021"


[dependencies]
diesel = { version = "2.1.4", features = ["sqlite"] }
dotenvy = "0.15"
tokio = {version = "1.36.0", features = ["full"]}
hyper = {version = "1.2.0", features = ["full"]}
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
