[package]
name = "zeusns"
version = "0.1.0"
edition = "2021"


[dependencies]
diesel = { version = "2.1.4", features = ["sqlite"] }
dotenvy = "0.15"
tokio = {version = "1.36.0", features = ["full"]}

