[package]
name = "zns-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
base64 = "0.22.0"
num-bigint = "0.4"
num-traits = "0.2"


[dependencies.zns]
version = "0.1.0"
path = "../zns"
